# Generated by Django 5.2.7 on 2025-10-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=255)),
                ('codigo_produto', models.CharField(max_length=50)),
                ('valores_mensais', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
