# Generated by Django 5.2.7 on 2025-11-21 02:09

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=255)),
                ('tipo_conta', models.CharField(choices=[('DGA', 'DGA'), ('Investimentos', 'Investimentos')], default='DGA', max_length=20, verbose_name='Tipo de conta')),
                ('codigo_produto', models.CharField(max_length=255)),
                ('valores_mensais', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
