# Generated by Django 5.2.7 on 2025-12-01 21:03

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=255)),
                ('justificativa', models.CharField(default='nenhuma', max_length=255)),
                ('tipo_conta', models.CharField(choices=[('DGA', 'DGA'), ('Investimentos', 'Investimentos')], default='DGA', max_length=20, verbose_name='Tipo de conta')),
                ('codigo_produto', models.JSONField(blank=True, default=list, verbose_name='Códigos de Produtos')),
                ('valores_mensais', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('e_recorrente', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='É Recorrente?')),
                ('obrigacao_legal', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Obrigação Legal?')),
            ],
        ),
    ]
