# Generated by Django 5.2.7 on 2025-12-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='codigo_produto',
            field=models.TextField(blank=True, default='', verbose_name='Códigos de Produtos'),
        ),
    ]
