# Generated by Django 5.2.7 on 2025-11-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='e_recorrente',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='É Recorrente?'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='obrigacao_legal',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Obrigação Legal?'),
        ),
    ]
