# Generated by Django 5.2.7 on 2025-11-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_projeto_e_recorrente_projeto_obrigacao_legal'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='justificativa',
            field=models.CharField(default='nenhuma', max_length=255),
        ),
    ]
