# Generated by Django 5.2.7 on 2025-11-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_projeto_valores_mensais'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='tipo_conta',
            field=models.CharField(choices=[('DGA', 'DGA'), ('Investimentos', 'Investimentos')], default='DGA', max_length=20, verbose_name='Tipo de conta'),
        ),
    ]
