# Generated by Django 5.2.7 on 2025-12-05 14:12

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_projeto_codigo_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoContaValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_contabil', models.CharField(max_length=255)),
                ('valores_mensais', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_valores', to='main.projeto')),
            ],
        ),
    ]
