# Generated by Django 5.2.7 on 2025-11-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_projeto_tipo_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='codigo_produto',
            field=models.CharField(max_length=255),
        ),
    ]
